---
apiVersion: v1
kind: Namespace
metadata:
  name: codeserver-ns1
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: codeserver-config 
  namespace: codeserver-ns1 
  labels:
    app: codeserver 
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-server.157.230.193.55.nip.io
---
apiVersion: v1
kind: Secret
metadata:
  name: codeserver-secret
  namespace: codeserver-ns1
  labels:
    app: codeserver
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=