---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: codeserver-pvc
    namespace: codeserver-ns1 
    labels:
        app: codeserver
        name: codeserver-pvc
spec:
    storageClassName: do-block-storage
    accessModes: [ ReadWriteOnce ]
    resources:
        requests:
            storage: 1Gi