---
apiVersion: v1
kind: Namespace
metadata:
  name: myns-2
  labels:
    app: bgg
---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
  namespace: myns-2
  labels:
    app: bgg
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=