---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: bggdb-deploy
  namespace: myns-2
  labels:
    app: bgg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg
      name: bggdb-po
  template:
    metadata:
      name: bggdb-po
      labels:
        app: bgg
        name: bggdb-po
    spec: 
      containers:
      - name: bggdb-container 
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3306
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3306
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc # service is in the same namespace as the pod that it's routing to
  namespace: myns-2
  labels:
    app: bgg
    name: bggdb-svc
spec:
  type: ClusterIP
  selector: # what are the pods that I want to deploy to
      app: bgg
      name: bggdb-po
  ports:
  - port: 3306
    targetPort: 3306 # the container port