--- 
# the three dashes represent one file (for each new resource) 
apiVersion: v1
kind: Pod
metadata:
  name: dov-po # name -po just to indicate that it's a pod (optional)
  namespace: myns
  labels: # key-value pairs, easy to search, can just specify whatever e.g. dept: eng
    app: dov
spec:
  containers: # each - is an element, must keep it aligned for each container
  - name: dov-container
    image: chukmunnlee/dov-bear:v5
    imagePullPolicy: IfNotPresent # pull if not present
    env:
    - name: INSTANCE_NAME
      value: "some instance name"
    - name: INSTANCE_HASH # can get the value of the env variable from somewhere else
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    ports:
    - containerPort: 3000 # specify port binding later
