---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-ns
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: minio-config 
  namespace: minio-ns 
  labels:
    app: minio 
data:
  address: ":9000"
  console-address: ":9090"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio-ns
  labels:
    app: minio
type: Opaque
data:
  MINIO_ROOT_USER: YWRtaW4=
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQ=
